apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprintbootservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprintbootservice1
  template:
    metadata:
      labels:
        app: sprintbootservice1
    spec:
      containers:
        - name: sprintbootservice1-container
          image: parit29/webapp:latest
          ports:
            - containerPort: 8080

