pipeline {
  agent any

  environment {
    IMAGE = "ghcr.io/ashu2356/webapp:18"
  }

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/Ashu2356/my-devops-project-2.git'
      }
    }

    stage('Build WAR') {
      steps {
        dir('SprintBootService-1') {
          sh 'mvn clean install'
        }
      }
    }

    stage('Build & Push Docker Image to GHCR') {
      steps {
        withCredentials([
          usernamePassword(credentialsId: 'dockerhub-user', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS'),
          usernamePassword(credentialsId: 'ghcr', usernameVariable: 'GHCR_USER', passwordVariable: 'GHCR_PASS')
        ]) {
          dir('SprintBootService-1') {
            sh '''
              echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
              echo $GHCR_PASS | docker login ghcr.io -u $GHCR_USER --password-stdin
              docker build -t $IMAGE .
              docker push $IMAGE
            '''
          }
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        withCredentials([file(credentialsId: 'k8s-kubeconfig', variable: 'KUBECONFIG')]) {
          dir('k8s') {
            sh '''
              kubectl apply -f deployment.yaml
              kubectl apply -f service.yaml
            '''
          }
        }
      }
    }
  }

  post {
    failure {
      echo "❌ Build or deployment failed."
    }
    success {
      echo "✅ Application successfully deployed to Kubernetes!"
    }
  }
}
